services:
  postgres:
    image: postgres:16
    container_name: leads-agro-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leads_agro
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
